//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YomiNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YomiNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.microsoft.com/en-us/microsoft-edge/webview2/.
        /// </summary>
        public static string MicrosoftEdgeWebView2Runtime_DownloadUrl {
            get {
                return ResourceManager.GetString("MicrosoftEdgeWebView2Runtime_DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/BornToBeRoot/YomiNet/blob/main/CONTRIBUTORS.
        /// </summary>
        public static string YomiNet_Contributors {
            get {
                return ResourceManager.GetString("YomiNet_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YomiNet.
        /// </summary>
        public static string YomiNet_GitHub_Repo {
            get {
                return ResourceManager.GetString("YomiNet_GitHub_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BornToBeRoot.
        /// </summary>
        public static string YomiNet_GitHub_User {
            get {
                return ResourceManager.GetString("YomiNet_GitHub_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/BornToBeRoot/YomiNet/issues/new/choose.
        /// </summary>
        public static string YomiNet_GitHubNewIssueUrl {
            get {
                return ResourceManager.GetString("YomiNet_GitHubNewIssueUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/BornToBeRoot/YomiNet.
        /// </summary>
        public static string YomiNet_GitHubRepoUrl {
            get {
                return ResourceManager.GetString("YomiNet_GitHubRepoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://borntoberoot.net/YomiNet/Download.
        /// </summary>
        public static string YomiNet_LatestReleaseUrl {
            get {
                return ResourceManager.GetString("YomiNet_LatestReleaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU General Public License v3.0.
        /// </summary>
        public static string YomiNet_License {
            get {
                return ResourceManager.GetString("YomiNet_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/BornToBeRoot/YomiNet/blob/main/LICENSE.
        /// </summary>
        public static string YomiNet_LicenseUrl {
            get {
                return ResourceManager.GetString("YomiNet_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YomiNet.
        /// </summary>
        public static string YomiNet_ProjectName {
            get {
                return ResourceManager.GetString("YomiNet_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://borntoberoot.net/YomiNet/.
        /// </summary>
        public static string YomiNet_ProjectUrl {
            get {
                return ResourceManager.GetString("YomiNet_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transifex.com/BornToBeRoot/YomiNet/.
        /// </summary>
        public static string YomiNet_TranslationUrl {
            get {
                return ResourceManager.GetString("YomiNet_TranslationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://x.com/_BornToBeRoot.
        /// </summary>
        public static string YomiNet_XContactUrl {
            get {
                return ResourceManager.GetString("YomiNet_XContactUrl", resourceCulture);
            }
        }
    }
}
